repos:
  # Basic file checks and formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        name: Check YAML syntax
      - id: check-toml
        name: Check TOML syntax
      - id: check-json
        name: Check JSON syntax
      - id: check-xml
        name: Check XML syntax
      - id: end-of-file-fixer
        name: Fix end of files
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: mixed-line-ending
        name: Check mixed line endings
        args: ["--fix=lf"]
      - id: check-executables-have-shebangs
        name: Check executables have shebangs
      - id: check-shebang-scripts-are-executable
        name: Check shebang scripts are executable
      - id: check-case-conflict
        name: Check for case conflicts
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-symlinks
        name: Check for broken symlinks
      - id: check-added-large-files
        name: Check for large files
        args: ["--maxkb=1024"] # 1MB limit
      - id: debug-statements
        name: Check for debug statements
      - id: detect-private-key
        name: Detect private keys
      - id: fix-byte-order-marker
        name: Fix byte order marker

  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        name: Ruff linter
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: Ruff formatter

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Sort imports
        args: [--profile, black, --line-length, "88"]

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        name: Shell script linter

  # # Documentation checks
  # - repo: local
  #   hooks:
  #     - id: interrogate
  #       name: Documentation coverage
  #       entry: uv run interrogate
  #       language: system
  #       types: [python]
  #       args: [--quiet, --fail-under=60, --ignore-init-method, --ignore-module]
